#ifndef _AC_GL_WRAPPER_H_
#define _AC_GL_WRAPPER_H_


enum glCommand { ACW_ACCUM, ACW_ALPHAFUNC, ACW_BEGIN, ACW_BLENDCOLOR, ACW_BLENDEQUATION, ACW_BLENDEQUATIONEXT, ACW_BLENDFUNC, ACW_CALLLIST, ACW_CLEAR, ACW_CLEARACCUM, ACW_CLEARCOLOR, ACW_CLEARDEPTH, ACW_CLEARINDEX, ACW_CLEARSTENCIL, ACW_COLOR3B, ACW_COLOR3BV, ACW_COLOR3D, ACW_COLOR3DV, ACW_COLOR3F, ACW_COLOR3FV, ACW_COLOR3I, ACW_COLOR3IV, ACW_COLOR3S, ACW_COLOR3SV, ACW_COLOR3UB, ACW_COLOR3UBV, ACW_COLOR3UI, ACW_COLOR3UIV, ACW_COLOR3US, ACW_COLOR3USV, ACW_COLOR4B, ACW_COLOR4BV, ACW_COLOR4D, ACW_COLOR4DV, ACW_COLOR4F, ACW_COLOR4FV, ACW_COLOR4I, ACW_COLOR4IV, ACW_COLOR4S, ACW_COLOR4SV, ACW_COLOR4UB, ACW_COLOR4UBV, ACW_COLOR4UI, ACW_COLOR4UIV, ACW_COLOR4US, ACW_COLOR4USV, ACW_COLORMASK, ACW_COLORMATERIAL, ACW_COPYPIXELS, ACW_CULLFACE, ACW_DEFORMSGIX, ACW_DELETELISTS, ACW_DEPTHFUNC, ACW_DEPTHMASK, ACW_DEPTHRANGE, ACW_DISABLE, ACW_DISABLECLIENTSTATE, ACW_DRAWARRAYS, ACW_DRAWARRAYSEXT, ACW_DRAWBUFFER, ACW_EDGEFLAG, ACW_ENABLE, ACW_ENABLECLIENTSTATE, ACW_END, ACW_ENDLIST, ACW_EVALCOORD1D, ACW_EVALCOORD1DV, ACW_EVALCOORD1F, ACW_EVALCOORD1FV, ACW_EVALCOORD2D, ACW_EVALCOORD2DV, ACW_EVALCOORD2F, ACW_EVALCOORD2FV, ACW_EVALMESH1, ACW_EVALMESH2, ACW_EVALPOINT1, ACW_EVALPOINT2, ACW_FLUSH, ACW_FLUSHRASTERSGIX, ACW_FOGF, ACW_FOGI, ACW_FRAMEZOOMSGIX, ACW_FRONTFACE, ACW_FRUSTUM, ACW_GENLISTS, ACW_GENTEXTURES, ACW_GETERROR, ACW_HINT, ACW_HISTOGRAM, ACW_HISTOGRAMEXT, ACW_INDEXMASK, ACW_INDEXD, ACW_INDEXF, ACW_INDEXI, ACW_INITNAMES, ACW_ISENABLED, ACW_ISLIST, ACW_ISTEXTURE, ACW_ISTEXTUREEXT, ACW_LIGHTMODELF, ACW_LIGHTMODELI, ACW_LIGHTF, ACW_LIGHTI, ACW_LINESTIPPLE, ACW_LINEWIDTH, ACW_LISTBASE, ACW_LISTPARAMETERFSGIX, ACW_LISTPARAMETERISGIX, ACW_LOADIDENTITY, ACW_LOADIDENTITYDEFORMATIONMAPSGIX, ACW_LOADNAME, ACW_LOGICOP, ACW_MATERIALF, ACW_MATERIALI, ACW_MATRIXMODE, ACW_MINMAX, ACW_MINMAXEXT, ACW_NEWLIST, ACW_NORMAL3B, ACW_NORMAL3BV, ACW_NORMAL3D, ACW_NORMAL3DV, ACW_NORMAL3F, ACW_NORMAL3FV, ACW_NORMAL3I, ACW_NORMAL3IV, ACW_NORMAL3S, ACW_NORMAL3SV, ACW_ORTHO, ACW_PASSTHROUGH, ACW_PIXELSTOREF, ACW_PIXELSTOREI, ACW_PIXELTEXGENSGIX, ACW_PIXELTRANSFERF, ACW_PIXELTRANSFERI, ACW_PIXELZOOM, ACW_POINTPARAMETERFSGIS, ACW_POINTSIZE, ACW_POLYGONMODE, ACW_POLYGONOFFSET, ACW_POLYGONOFFSETEXT, ACW_POPATTRIB, ACW_POPCLIENTATTRIB, ACW_POPMATRIX, ACW_POPNAME, ACW_PUSHATTRIB, ACW_PUSHCLIENTATTRIB, ACW_PUSHMATRIX, ACW_PUSHNAME, ACW_RASTERPOS2D, ACW_RASTERPOS2DV, ACW_RASTERPOS2F, ACW_RASTERPOS2FV, ACW_RASTERPOS2I, ACW_RASTERPOS2IV, ACW_RASTERPOS2S, ACW_RASTERPOS2SV, ACW_RASTERPOS3D, ACW_RASTERPOS3DV, ACW_RASTERPOS3F, ACW_RASTERPOS3FV, ACW_RASTERPOS3I, ACW_RASTERPOS3IV, ACW_RASTERPOS3S, ACW_RASTERPOS3SV, ACW_RASTERPOS4D, ACW_RASTERPOS4DV, ACW_RASTERPOS4F, ACW_RASTERPOS4FV, ACW_RASTERPOS4I, ACW_RASTERPOS4IV, ACW_RASTERPOS4S, ACW_RASTERPOS4SV, ACW_READBUFFER, ACW_READINSTRUMENTSSGIX, ACW_RECTD, ACW_RECTF, ACW_RECTI, ACW_RECTS, ACW_RENDERMODE, ACW_ROTATEF, ACW_SAMPLEMASKSGIS, ACW_SAMPLEPATTERNSGIS, ACW_SCALED, ACW_SCALEF, ACW_SCISSOR, ACW_SHADEMODEL, ACW_STARTINSTRUMENTSSGIX, ACW_STENCILFUNC, ACW_STENCILMASK, ACW_STENCILOP, ACW_STOPINSTRUMENTSSGIX, ACW_TAGSAMPLEBUFFERSGIX, ACW_TEXCOORD1D, ACW_TEXCOORD1DV, ACW_TEXCOORD1F, ACW_TEXCOORD1FV, ACW_TEXCOORD1I, ACW_TEXCOORD1IV, ACW_TEXCOORD1S, ACW_TEXCOORD1SV, ACW_TEXCOORD2D, ACW_TEXCOORD2DV, ACW_TEXCOORD2F, ACW_TEXCOORD2FV, ACW_TEXCOORD2I, ACW_TEXCOORD2IV, ACW_TEXCOORD2S, ACW_TEXCOORD2SV, ACW_TEXCOORD3D, ACW_TEXCOORD3DV, ACW_TEXCOORD3F, ACW_TEXCOORD3FV, ACW_TEXCOORD3I, ACW_TEXCOORD3IV, ACW_TEXCOORD3S, ACW_TEXCOORD3SV, ACW_TEXCOORD4D, ACW_TEXCOORD4DV, ACW_TEXCOORD4F, ACW_TEXCOORD4FV, ACW_TEXCOORD4I, ACW_TEXCOORD4IV, ACW_TEXCOORD4S, ACW_TEXCOORD4SV, ACW_TEXENVF, ACW_TEXENVI, ACW_TEXGEND, ACW_TEXGENF, ACW_TEXGENI, ACW_TEXPARAMETERF, ACW_TEXPARAMETERI, ACW_TRANSLATED, ACW_TRANSLATEF, ACW_VERTEX2D, ACW_VERTEX2DV, ACW_VERTEX2F, ACW_VERTEX2FV, ACW_VERTEX2I, ACW_VERTEX2IV, ACW_VERTEX2S, ACW_VERTEX2SV, ACW_VERTEX3D, ACW_VERTEX3DV, ACW_VERTEX3F, ACW_VERTEX3FV, ACW_VERTEX3I, ACW_VERTEX3IV, ACW_VERTEX3S, ACW_VERTEX3SV, ACW_VERTEX4D, ACW_VERTEX4DV, ACW_VERTEX4F, ACW_VERTEX4FV, ACW_VERTEX4I, ACW_VERTEX4IV, ACW_VERTEX4S, ACW_VERTEX4SV, ACW_VIEWPORT };


#include <GL/gl.h>
#include <stdlib.h>
#include <string.h>
	
void acGLWrapStart();
void acGLWrapFinish();
void acGLWrapSetBuffer( unsigned char* B, long Bsize );
void* acGLWrapGetBuffer();
long acGLWrapGetBufferSize();

/* data read and apply calls */
void acGLWrapApply();

  

#endif

